project_id = "pmkhyxlpaclserfbkxka"

[functions.onboarding-assistant]
verify_jwt = true

[functions.retry-onboarding-routines]
verify_jwt = true

[functions.materialize-tasks]
verify_jwt = false

[functions.materialize-tasks-v2]
verify_jwt = false

[functions.update-urgency]
verify_jwt = false

[functions.defer-tasks]
verify_jwt = false

[functions.set-pin]
verify_jwt = true

[functions.verify-pin]
verify_jwt = false